export const teamMembers = [
    {
        image: 'team_images/prof_isaac_k_nyamongo.jpg',
        name: 'Prof. Isaac K. Nyamongo',
        position: 'Principal Investigator (PI)',
        description: 'Prof. Isaac K. Nyamongo is a distinguished Anthropology Professor and Deputy Vice-Chancellor at the Cooperative University of Kenya. With extensive research and training grants from prestigious organizations, including the EU and WHO, his work spans multiple African countries to focus on the social drivers of human development. Prof. Nyamongo is the current President of the World Anthropological Union.',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/dr_cherie_enns.jpg',
        name: 'Dr Cherie Enns',
        position: 'Co-Principal Investigator (Co-PI)',
        description: 'Dr. Cherie Enns is a registered urban planner and esteemed educator. Dr. Enns has extensive international engagement experience and has led impactful projects worldwide, focusing on human rights, sustainable development goals, urban planning policy, and food systems. Dr. Enns is a respected University of the Fraser Valley professor in the Planning, Geography, and Environmental Studies Department. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/dr_charles_wambu.jpg',
        name: 'Dr David Obonyo',
        position: 'Decision Maker, Co-Principal Investigator (Co-PI)',
        description: 'Mr. David Obonyo has been the Commissioner for Cooperatives in Kenya since 2021. Mr. Obonyo is a career civil servant and has served in cooperative administration since 1990, focusing mainly on cooperative development. He holds a Master\'s Degree in Arts, Rural Economics and Co-Operation, and has attended various local and international courses on strategic leadership.',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/prof_kennedy_waweru.jpg',
        name: 'Prof. Kennedy Waweru',
        position: 'Research Associate (Finance)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/prof_wycliffe_oboka.jpg',
        name: 'Prof. Wycliffe Oboka',
        position: 'Research Associate (Disaster Management)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/dr_charles_wambu.jpg',
        name: 'Dr Charles Wambu',
        position: 'Research Associate (Gender)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/prof_salome_bukachi.jpg',
        name: 'Prof. Salome Bukachi',
        position: 'Research Associate (Gender)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/kristin_swardh.jpg',
        name: 'Kristin Swardh',
        position: 'Research Associate (Gender) and Project Manager',
        description: 'Ms. Kristin Swardh, MSW, RSW, is a registered social worker with a Master of Social Work degree specializing in Social Justice and Diversity. She has extensive experience in interdisciplinary social work practice across Canada, the African continent and Central America, with work in government, academia and non-profit sectors to bring a social justice lens to projects or programmes.',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/profilepic.png',
        name: 'Douglas Nyambane Anyona',
        position: 'Project Manager',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/edith_kemunto.jpg',
        name: 'Edith Kemunto',
        position: 'Research Associate (Gender)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/silas_maiyo.jpg',
        name: 'Silas Maiyo',
        position: 'Research Associate (Innovation Design)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/victor_wambua.jpg',
        name: 'Victor Wambua',
        position: 'Research Associate (Cooperative Management)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/monica_chepkurui.jpg',
        name: 'Monica Chepkurui',
        position: 'Research Associate (Cooperative Management)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/mary_mbugua.jpg',
        name: 'Mary Mbugua',
        position: 'Research Associate (Cooperative Management)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/profilepic.png',
        name: 'Abbey Lin',
        position: 'Research Assistant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/timothy_kagiri.jpg',
        name: 'Timothy Kagiri',
        position: 'Research Assistant (Health)',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/jacqueline_fanta.jpg',
        name: 'Jacqueline Fanta',
        position: 'Social Media Coordinator',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    }, 
    {
        image: 'team_images/brandon_wirsz.jpg',
        name: 'Brandon wirsz',
        position: 'Public Relations Coordinator',
        description: 'Brandon Wirsz is a professional communicator with experience in copywriting, social media, strategy design and influencer marketing. He has worked with notable lifestyle and food and beverage brands and holds a Diploma in Public Relations from Kwantlen Polytechnic University. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    },
    {
        image: 'team_images/jared_murundu.jpg',
        name: 'Jared Murundu',
        position: 'Research Assistant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    }, 
    {
        image: 'team_images/profilepic.png',
        name: 'Jocinter Atieno',
        position: 'Research Assistant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    }, 
    {
        image: 'team_images/aloo_filomena_ayango.jpg',
        name: 'Aloo Filomena Ayango',
        position: 'Research Assistant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    }, 
    {
        image: 'team_images/francis_ajega_luyayi.jpg',
        name: 'Francis Ajega Luyayi',
        position: 'Research Assistant',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.  Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. ',
        socialMedia: {
            facebook: 'https://www.linkedin.com/company/winrack/',
            twitter: 'https://www.linkedin.com/company/winrack/',
            linkedin: 'https://www.linkedin.com/company/winrack/',
          },
    }, 
];